In [1]:
import numpy as np

In [2]:
arr=np.array([45,67,9,8])
print(arr)

[45 67  9  8]


In [3]:
arr.shape

(4,)

In [4]:
arr.size

4

In [5]:
#slice 
print(arr[2:4])

[9 8]


In [6]:
print(np.__version__)

2.3.2


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
print(arr[0])

45


In [9]:
#2-d array
s=np.array([[1,2,3],[2,3,6]])
print(s)

[[1 2 3]
 [2 3 6]]


In [2]:
print(s[0,2])

NameError: name 's' is not defined

In [11]:
print(s.size)

6


In [12]:
print(s.shape)

(2, 3)


In [13]:
print(s[1,2]+s[0,2])

9


In [14]:
# 3d array
j=np.array([[[1,2,3],[5,6,7]],[[5,6,7],[3,4,5]]])
j

array([[[1, 2, 3],
        [5, 6, 7]],

       [[5, 6, 7],
        [3, 4, 5]]])

In [15]:
#print index value of j(-1 means last element of our list)
print(j[0,1,2])
print(j[1,1,-1])
print(j[-1,1,0])
print(j[-1,-1,-1])

7
5
3
5


In [16]:
#slice 1d array
k=np.array([1,2,3,4,5,6,7,8,7],ndmin())
print(j[::-1])

NameError: name 'ndmin' is not defined

In [17]:
#slice 1d array
print(k[4:])
print(k[:5:])
print(k[2:9:2])
print(k[:4])

NameError: name 'k' is not defined

In [18]:
#slice 1d array
print(k[::-1])
print(k[-1::-1])
print(k[-2:-9:-1])
print(k[-3:-1])
print(k[::2])

NameError: name 'k' is not defined

In [ ]:
#slicing in 2 d array
are = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(are[1,1:5])
print(are[0,0:5:])
print(are[-1::])
print(are[0,0:-1])
print(are[0:3,3])
print(are[0:2,1:4])


In [19]:
#data types

print(are.dtype)


NameError: name 'are' is not defined

In [ ]:
# u6 u7 based on maaaximum length of string
f=np.array(["jiya","sandhya"])
print(f.dtype)
ff=np.array(["apple","banana"])
print(ff.dtype)

In [20]:
#only same data type element can be passed otherwise can be created
rr = np.array(['9', '2', '3'], dtype='i')
rr
arr = np.array(['a', '2', '3'], dtype='i')
arr


ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#'astype' convert datatype
arr=np.array([2.2,2,4.5,55.4])
are=arr.astype(int)
print(are)
print(arr)
print(k.astype(float))
print(k.astype(bool))

In [21]:
#astype convert into other datatype 
a=np.array([-1,1,0])
print(a.astype(bool))

[ True  True False]


In [22]:
"""NumPy uses a character to represent each of the following data types, which one?
i = integer
b = boolean
u = unsigned integer
f = float
c = complex float
m = timedelta
M = datetime
O = object
S = string"""

'NumPy uses a character to represent each of the following data types, which one?\ni = integer\nb = boolean\nu = unsigned integer\nf = float\nc = complex float\nm = timedelta\nM = datetime\nO = object\nS = string'

In [23]:
#shape
k=np.array([2,33,4,5,6])
print(k.size)
print(k.shape)

5
(5,)


In [24]:
#ndmin
k=np.array([2,33,4,5,6],ndmin=3)
print(k)

[[[ 2 33  4  5  6]]]


In [25]:
py=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
pyn=py.reshape(2,6)
print(pyn)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 11, 12])

newarr = arr.reshape(3, 3)

print(newarr)
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print(arr.reshape(4,2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7 11 12]]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [27]:
"""7. NumPy Array Iterating
Iterating means going through elements one by one.
As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
If we iterate on a 1-D array it will go through each element one by one."""

arr=np.array([1,2,3])
for x in arr:
    print(x)


1
2
3


In [29]:
#Iterating 2-d array
arr=np.array([[12,3,4],[3,4,5]])
for x in arr:
    print(x)
    

[12  3  4]
[3 4 5]


In [36]:
#Splitting NumPy Arrays
l=np.array([2,3,4,5,6,888,9,3])
s=np.array_split(l,3)
print(s)

[array([2, 3, 4]), array([  5,   6, 888]), array([9, 3])]


In [38]:
##Searching array(where)
arr=np.array([4,4,5,6,67,8])
print(np.where(arr==67))
print(np.where(arr==0))

(array([4]),)
(array([], dtype=int64),)


In [40]:
#sorting arrays
arr=np.array([3,4,5,0,7])
print(np.sort(arr))

[0 3 4 5 7]


In [54]:
#mathematical function
print("add",np.add(2,3))
print("sub",np.subtract(5,6))
print("mul",np.multiply(4,5))
print("div",np.divide(4,5))
print("power",np.power(2,3))
print("cube root",np.cbrt(3))
print("square root",np.sqrt(2))
print("exponential",np.exp(3))
print(np.log(23))
print(np.sin(23))

add 5
sub -1
mul 20
div 0.8
power 8
cube root 1.4422495703074083
square root 1.4142135623730951
exponential 20.085536923187668
3.1354942159291497
-0.8462204041751706
