In [1]:
import numpy as np

In [2]:
store=np.array([1,2,3,4,5,6],np.int32)

In [3]:
store

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [4]:
store=np.array([1,2,3,4,5,36376],np.int32)
store

array([    1,     2,     3,     4,     5, 36376], dtype=int32)

In [5]:
store[5]

np.int32(36376)

In [6]:
## 2 d array[[array]]
listarray=np.array([[1,2,3],[3,4,5],[85,5,67]],np.int8)
store

array([    1,     2,     3,     4,     5, 36376], dtype=int32)

In [7]:
listarray[1,2]

np.int8(5)

In [8]:
listarray.size

9

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.dtype

dtype('int8')

In [11]:
zeros=np.zeros([4,4])#zeros=np.zeros((4,4)) also can do
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
zeros.dtype

dtype('float64')

In [13]:
zeros.shape

(4, 4)

In [14]:
zeros.size

16

In [15]:
rng=np.arange(19)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [16]:
#linspace give linear spaces element 
lspace=np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [17]:
#empty array
ep=np.empty((2,3))
ep

array([[2.14321575e-312, 2.35541533e-312, 9.76118064e-313],
       [2.20687562e-312, 2.37663529e-312, 7.56571287e-307]])

In [18]:
#like empty array
emp_like=np.empty_like((lspace))
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [19]:
ep_like=np.empty_like((ep))
ep_like

array([[2.14321575e-312, 2.35541533e-312, 9.76118064e-313],
       [2.20687562e-312, 2.37663529e-312, 7.56571287e-307]])

In [20]:
long=np.empty((6,3))
long

array([[1.37962049e-306, 1.24610791e-306, 1.11260959e-306],
       [1.69109959e-306, 9.34603679e-307, 1.42419802e-306],
       [1.78019082e-306, 4.45061456e-308, 1.24612081e-306],
       [1.37962049e-306, 9.34597567e-307, 1.29061821e-306],
       [1.78019625e-306, 1.11255866e-306, 8.90098127e-307],
       [9.34609790e-307, 3.91792279e-317, 1.04718096e-142]])

In [21]:
#reshape array
arr=np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [22]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [23]:
# reshape elemrnt must be multiple of arange
arr.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [24]:
# for i d array
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [25]:
arr.shape

(100,)

In [26]:
myarr=np.array([[1,2,3],[9,0,9],[8,9,0]])
myarr

array([[1, 2, 3],
       [9, 0, 9],
       [8, 9, 0]])

In [27]:
# for axis=0 add all rows 
myarr.sum(axis=0)

array([18, 11, 12])

In [28]:
# for axis=1 add all coloum
myarr.sum(axis=1)

array([ 6, 18, 17])

In [29]:
tranpose=np.transpose(myarr)
tranpose

array([[1, 9, 8],
       [2, 0, 9],
       [3, 9, 0]])

In [30]:
myarr.flat

In [31]:
for item in myarr.flat:
    print(item)

1
2
3
9
0
9
8
9
0


In [32]:
myarr.ndim

2

In [33]:
#explain bytes
myarr.nbytes

72

In [34]:
#one d array 
one=np.array([1,2,4,900,6,7])
one.argmax()

np.int64(3)

In [35]:
#show min element index
one.argmin()

np.int64(0)

In [36]:
#sorthing array
one.argsort()

array([0, 1, 2, 4, 5, 3])

In [37]:

arr=np.array([[1,2,3],[3,3,4],[3,4,5]])
arr

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [38]:
#argmin index of minimun element and opposite for argmax
arr.argmin(axis=1)


array([0, 0, 0])

In [39]:
arr.argmax(axis=1)


array([2, 2, 2])

In [40]:
#sort
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [41]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [42]:
arr.ravel()

array([1, 2, 3, 3, 3, 4, 3, 4, 5])

In [43]:
arr

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [44]:
arr2=np.array([[2,3,4],[1,2,3],[0, 1, 2]])
arr2

array([[2, 3, 4],
       [1, 2, 3],
       [0, 1, 2]])

In [45]:
arr+arr2

array([[3, 5, 7],
       [4, 5, 7],
       [3, 5, 7]])

In [46]:
arr*arr2

array([[ 2,  6, 12],
       [ 3,  6, 12],
       [ 0,  4, 10]])

In [47]:
arr-arr2

array([[-1, -1, -1],
       [ 2,  1,  1],
       [ 3,  3,  3]])

In [48]:
[2,3,4]+[3,4,7.8]

[2, 3, 4, 3, 4, 7.8]

In [49]:
arr=np.array([[1,2,3],[3,3,4],[3,4,5]])
arr2=np.array([[2,3,4],[1,2,3],[0, 1, 2]])

p=arr**arr2
q=arr//arr2
print(p,2*"\n",q)

[[ 1  8 81]
 [ 3  9 64]
 [ 1  4 25]] 

 [[0 0 0]
 [3 1 1]
 [0 4 2]]


C:\Users\jiyad\AppData\Local\Temp\ipykernel_9772\2322213735.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  q=arr//arr2


In [50]:
arr.sum()

np.int64(28)

In [51]:
arr.max()


np.int64(5)

In [52]:
arr.min()

np.int64(1)

In [53]:
arr

array([[1, 2, 3],
       [3, 3, 4],
       [3, 4, 5]])

In [54]:
#find the array by index
np.where(arr>4)


(array([2]), array([2]))

In [55]:
type(np.where(arr>4))

tuple

In [56]:
#count non zero element
np.count_nonzero(arr2)

8

In [57]:
arr[1,1]=0

In [58]:
np.count_nonzero(arr)

8

In [59]:
np.nonzero(arr)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 2, 0, 1, 2]))

In [60]:
import sys

In [61]:
py_ar=[1,2,3,4]

In [62]:
np_ar=np.array([1,2,3,4])

In [63]:
#normal python get large bit and more space
sys.getsizeof(1) * len(py_ar)

112

In [64]:
#numpy occupy less space
np_ar.itemsize * np_ar.size

32

In [77]:
j=np.array([4,5,6])
r=np.array([6,7,8])
k=j+r
l=[]
o=(np.sum(j))
l.append(o)
p=(np.sum(k))
l.append(p)
l
m=np.max(l)
print(l,m)
print(np.where(l==m))

[np.int64(15), np.int64(36)] 36
(array([1]),)


In [ ]:
j=np.array([4,5,6])
np.where(

In [ ]:
import datetime
j=np.array([4,5,6])
r=np.array([6,7,8])
