In [1]:
import keyword

In [3]:
#print keywords and reserved words
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [11]:
a=46543
b=0b0101
c=0o756475
d=0x75543576af
print("DECIMAL : ",a,"BINARY :",b,"OCTALE :",c,"HEXADECIMAL :",d)

DECIMAL :  46543 BINARY : 5 OCTALE : 253245 HEXADECIMAL : 503923963567


In [3]:
a=1.2e3
print(a)

1200.0


In [7]:
#complex number
a=0b1111+20j

print(a)

(15+20j)


In [8]:
b=20+0b1111j
b

SyntaxError: invalid binary literal (2212805332.py, line 1)

In [12]:
a=20+30j
print(a.real)
print(a.imag)

20.0
30.0


In [14]:
a=True*True+True+True
a

3

In [17]:
a=True+True # 1+1=2
b=False+False # 0+0=0
c=True+False #1+0=1
print(a,b,c)

2 0 1


In [20]:
name="jiya"
lastname=" deshmukh"
print(name+lastname)
print(type(name))

jiya deshmukh
<class 'str'>


In [25]:
a="jiya"
b="10"
print(a+b)

jiya10


In [24]:
a="riya"
print(a*3)

riyariyariya


In [28]:
#indexing
print(a[2])

y


In [52]:
#slicing
c="Acropolis"
print(c[0:4])
print(c[:])
print(c[:4])
print(c[-1::-1])
print(c[::2])
print(c[2::3])
h="hello"
print(h[-1::-1])
print(h[-1:-1]) # blank output
print(c[2::2])
print(c[::-1])

Acro
Acropolis
Acro
siloporcA
Arpls
ros
olleh

rpls
siloporcA


In [53]:
import numpy as np
a=np.array([[1,2,3],[2,4,6],[3,6,9]])
print(a)
          

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [61]:
print(a[0,2])

TypeError: 'int' object is not subscriptable

In [58]:
a=int(input("enter a : "))
b=int(input("enter b : "))
print("sum of a and b :",a+b)

enter a :  7
enter b :  8


sum of a and b : 15


In [4]:
#type conversion
#int
int(10.5)
int(True)
int("10")
str("jiya")

'jiya'

In [7]:
#float
a=float(10)
b=float(True)
c=float("10")
d=float("10.5")
print(a,b,c,d)

10.0 1.0 10.0 10.5


In [12]:
#complex
a=complex(67)
b=complex(33,44)
c=complex(10)
d=complex(10.5+6)
e=complex(True)
f=complex(False)
print(a,b,c,d,e,f)

(67+0j) (33+44j) (10+0j) (16.5+0j) (1+0j) 0j


In [16]:
#bool
a=bool(0)
n=bool(10)

m=bool(10+20j)
o=bool(0+0j)
j=bool(0+1j)
h=bool("jiiya")
print(a,n,m,o,j,h)

False True True False True True


In [ ]:
#check string is palindrom or not
#average of three number
#simple interest



In [19]:
#a=int(input("enter number"))
a=212
add=0
rem=a%10
rev=a/10
add+=rem



    

TypeError: 'int' object is not subscriptable

In [17]:
#average of three number
a=int(input("enter a"))
b=int(input("enter b"))
c=int(input("enter c"))
add=a+b+c
ave=add/3
print(ave)


enter a 2
enter b 4
enter c 6


4.0


In [18]:
pri=int(input("enter principle"))
rate=int(input("enter rate"))
time=int(input("enter time"))
multi=pri*rate*time
simple_intereser=multi/100
print(simple_intereser)

enter principle 400
enter rate 2
enter time 1


8.0
